service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

mockpayment:
  enabled: false
  replicas: 1
  image: docker.io/openmf/ph-ee-connector-mock-payment-schema:v1.0.0
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  DFSPIDS: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: { }
  ingress:
    enabled: true
    annotations: { }
    # kubernetes.io/ingress.class: "nginx"
    pathtype: ImplementationSpecific
    hosts:
      - host: ""
        paths:
          - path: /
    tls: [ ]
    #  - secretName: sandbox-secret
    #    hosts:
    #      - chart-example.local